mode: controller
interval: 10
timeout: 2

image:
  repository: ghcr.io/cyberun-cloud/simple-gslb
  # tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

controller:
  geoip: false

geoip:
  account: ""
  license: ""
