apiVersion: v1
kind: Service
metadata:
  name: simplegslb-{{ .Release.Name }}
spec:
  selector:
    app: simplegslb-{{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    {{- if eq .Values.mode "controller" }}
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    {{- end }}
